name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer dependencies
        run: |
          cd backend_laravel
          composer install --no-dev --optimize-autoloader

      - name: Prepare Laravel for Production
        run: |
          cd be
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: nama-app-service-kamu
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./be
